---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

resources:
  requests:
    cpu: 2000
    memory: 4000MiB

steps:
  - name: Build front end
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:latest
    environment:
      CI: false
    commands:
      - cd react
      - pwd && yarn install
      - pwd && yarn build
    when:
      event:
        - push

  - name: Copy front end to resources
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:latest
    commands:
      - pwd && rm -rf ./src/main/resources/frontend
      - pwd && mv ./react/build ./src/main/resources/frontend
    when:
      event:
        - push
    depends_on:
      - Build front end

  - name: Test back end
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:latest
    commands:
      - /root/entrypoint.sh
      - sbt -mem 2048 test
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: scala-test-token
    when:
      event:
        - push
    depends_on:
      - Copy front end to resources

  - name: Build docker image
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:latest
    commands:
      - /root/entrypoint.sh
      - sbt docker:stage
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: scala-test-token
    when:
      event:
        - push
    depends_on:
      - Test back end

  - name: publish
    image: plugins/ecr
    environment:
      AWS_REGION: eu-west-2
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      repo: drt/drt-dashboard
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      tags:
        - B${DRONE_BUILD_NUMBER}
        - latest
    when:
      event:
        - push
    depends_on:
      - Build docker image
      - Copy front end to resources

...
