---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

steps:
  - name: Build and test front end
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    environment:
      CI: false
    commands:
      - cd react
      - pwd && npm install
      - pwd && npm run build
      - pwd && npm run test-ci
    when:
      event:
        - push

  - name: Copy front end to resources
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - pwd && rm -rf ./src/main/resources/frontend
      - pwd && mv ./react/build ./src/main/resources/frontend
    when:
      event:
        - push
    depends_on:
      - Build and test front end

  - name: Unit tests
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt -mem 2048 test
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
    when:
      event:
        - push
    depends_on:
      - Copy front end to resources

  - name: Build docker image
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt docker:stage
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
    when:
      event:
        - push
    depends_on:
      - Unit tests

  - name: Publish app
    image: plugins/ecr
    environment:
      AWS_REGION: eu-west-2
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      repo: drt/drt-dashboard
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      tags:
        - B${DRONE_BUILD_NUMBER}
        - latest
    when:
      event:
        - push
    depends_on:
      - Build docker image
      - Copy front end to resources

  - name: Code coverage report
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt -mem 4096 coverage test coverageOff coverageReport
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
      ENV_LOG_LEVEL: ERROR
    when:
      event:
        - push
    depends_on:
      - Publish app

  - name: Scapegoat
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt scapegoat | true
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
      ENV_LOG_LEVEL: ERROR
    when:
      event:
        - push
    depends_on:
      - Code coverage report

  - name: pull-image-for-scan
    pull: Always
    image: quay.io/ukhomeofficedigital/dind-awscli:19.03.12-dind-1.18.55
    resources:
      limits:
        cpu: 100
        memory: 256Mi
    commands:
      - n=0; until docker info >/dev/null 2>&1 || [ "$n" -ge 60 ]; do n=$(( n + 1 )); sleep 1; done
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      - docker pull 340268328991.dkr.ecr.eu-west-2.amazonaws.com/drt/drt-dashboard:B${DRONE_BUILD_NUMBER}
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-2
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
    when:
      event:
        - push
    depends_on:
      - Publish app

  - name: scan-image
    pull: Always
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    resources:
      limits:
        cpu: 1000
        memory: 1024Mi
    environment:
      FAIL_ON_DETECTION: false
      SEVERITY: MEDIUM,HIGH,CRITICAL
      IMAGE_NAME: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/drt/drt-dashboard:B${DRONE_BUILD_NUMBER}
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-2
    when:
      event:
        - push
    depends_on:
      - pull-image-for-scan

  - name: Sonar scanner
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/sonar-scanner:v7.3
    commands:
      - sonar-scanner -Dsonar.projectVersion=B${DRONE_BUILD_NUMBER} -X
    environment:
      DRONE_BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
    when:
      event:
        - push
    depends_on:
      - Scapegoat

  - name: Slack notification
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: devs
      template: "*{{repo.name}}: _{{build.status}}_*\nCompleted build *{{build.number}}* after *{{since build.started}}* on *{{build.branch}}*\n{{build.link}}\n"
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status:
        - success
        - failure
      event:
        - push
    depends_on:
      - Publish app
      - Unit tests

...
