pipeline:

  build:
    image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
      - /root/entrypoint.sh
      - sbt test buildReactApp docker:stage
    environment:
      - ARTIFACTORY_USERNAME=drt_artifactory
    secrets:
      - ARTIFACTORY_PASSWORD
      - GOV_NOTIFY_API_KEY
    when:
      event:
        - push

  build_push_to_ecr:
    image: quay.io/ukhomeofficedigital/ecr:latest
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/drt/drt-dashboard
    build_args:
      - APP_BUILD=${DRONE_COMMIT_SHA}
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
    when:
      event:
        - push
