---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: Build front end
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.2.0-beta1
    environment:
      CI: false
    commands:
      - cd react
      - pwd && yarn install
      - pwd && yarn build
    when:
      event:
        - push

  - name: Copy front end to resources
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.0.0
    commands:
      - pwd && rm -rf ./src/main/resources/frontend
      - pwd && mv ./react/build ./src/main/resources/frontend
    when:
      event:
        - push
    depends_on:
      - Build front end

  - name: Test back end
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.0.0
    commands:
      - /root/entrypoint.sh
      - sbt -mem 2048 test
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
    when:
      event:
        - push
    depends_on:
      - Copy front end to resources

  - name: analysis
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.0.0
    commands:
      - /root/entrypoint.sh
      - sbt -ivy ./.ivy2 dependencyCheck
      - sbt -ivy ./.ivy2 -mem 4096 -J-XX:+UseG1GC clean coverage test coverageReport
      - sbt scalastyle | true
      - sbt scapegoat | true
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
      ENV_LOG_LEVEL: ERROR
    when:
      branch: leader
      event:
        - push

  - name: sonar-scanner
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/sonar-scanner:v4.6
    commands:
      - sonar-scanner -Dsonar.projectVersion=B${DRONE_BUILD_NUMBER}
    environment:
      DRONE_BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
    when:
      event:
        - push
    depends_on:
      - analysis

  - name: Build docker image
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.0.0
    commands:
      - /root/entrypoint.sh
      - sbt docker:stage
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
    when:
      event:
        - push
    depends_on:
      - Test back end

  - name: publish
    image: plugins/ecr
    environment:
      AWS_REGION: eu-west-2
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      repo: drt/drt-dashboard
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      tags:
        - B${DRONE_BUILD_NUMBER}
        - latest
    when:
      event:
        - push
    depends_on:
      - Build docker image
      - Copy front end to resources

  - name: slack_notification
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: devs
      template: "*{{repo.name}}: _{{build.status}}_*\nCompleted build *{{build.number}}* after *{{since build.started}}* on *{{build.branch}}*\n{{build.link}}\n"
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status:
        - success
        - failure
      event:
        - push
    depends_on:
      - publish
      - Test back end

...
